/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/extract.json
export type NoteAside = {
  _type: "noteAside";
  title: string;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<
      {
        _key: string;
      } & Link
    >;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  tone: "note" | "caution";
};

export type ImageGallery = {
  _type: "imageGallery";
  images: Array<
    {
      _key: string;
    } & CaptionedImage
  >;
  layout: "grid" | "sideBySide";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type CaptionedImage = {
  _type: "captionedImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: string;
  caption?: string;
  credit?: string;
};

export type PullQuote = {
  _type: "pullQuote";
  quote: string;
  attribution?: string;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Link = {
  _type: "link";
  href: string;
  openInNewTab?: boolean;
};

export type SimpleText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal";
  listItem?: never;
  markDefs?: Array<
    {
      _key: string;
    } & Link
  >;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<
        {
          _key: string;
        } & Link
      >;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & PullQuote)
  | ({
      _key: string;
    } & CaptionedImage)
  | ({
      _key: string;
    } & ImageGallery)
  | ({
      _key: string;
    } & NoteAside)
>;

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description: string;
  defaultOgImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  navigation?: Array<{
    label: string;
    href: string;
    _key: string;
  }>;
  footerText?: string;
  socialLinks?: Array<{
    label: string;
    url: string;
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  body?: BlockContent;
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Topic = {
  _id: string;
  _type: "topic";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type IssueReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "issue";
};

export type TopicReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "topic";
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  standfirst: string;
  body?: BlockContent;
  author: AuthorReference;
  issue?: IssueReference;
  topics?: Array<
    {
      _key: string;
    } & TopicReference
  >;
  publishedAt: string;
  featured?: boolean;
  seo?: Seo;
};

export type Issue = {
  _id: string;
  _type: "issue";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  number: number;
  title: string;
  slug: Slug;
  publishedAt: string;
  introduction?: BlockContent;
  colophon?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  role?: string;
  bio?: SimpleText;
  links?: Array<{
    label: string;
    url: string;
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | NoteAside
  | ImageGallery
  | SanityImageAssetReference
  | CaptionedImage
  | PullQuote
  | Seo
  | Link
  | SimpleText
  | BlockContent
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | Page
  | Slug
  | Topic
  | AuthorReference
  | IssueReference
  | TopicReference
  | Article
  | Issue
  | Author
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: siteSettingsQuery
// Query: *[_id == "siteSettings"][0]{    title,    description,    defaultOgImage {  ...,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height, aspectRatio}}  }},    navigation[]{label, href},    footerText,    socialLinks[]{label, url}  }
export type SiteSettingsQueryResult =
  | {
      title: null;
      description: null;
      defaultOgImage: null;
      navigation: null;
      footerText: null;
      socialLinks: null;
    }
  | {
      title: string;
      description: null;
      defaultOgImage: null;
      navigation: null;
      footerText: null;
      socialLinks: null;
    }
  | {
      title: string;
      description: string | null;
      defaultOgImage: null;
      navigation: null;
      footerText: null;
      socialLinks: null;
    }
  | {
      title: string | null;
      description: string | null;
      defaultOgImage: null;
      navigation: null;
      footerText: null;
      socialLinks: null;
    }
  | {
      title: string;
      description: string;
      defaultOgImage: {
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number;
              height: number;
              aspectRatio: number;
            } | null;
          } | null;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      navigation: Array<{
        label: string;
        href: string;
      }> | null;
      footerText: string | null;
      socialLinks: Array<{
        label: string;
        url: string;
      }> | null;
    }
  | null;

// Source: sanity/lib/queries.ts
// Variable: homeQuery
// Query: {  "featured": *[_type == "article" && featured == true]    | order(publishedAt desc)[0]{  _id,  title,  "slug": slug.current,  standfirst,  publishedAt,  featured,  "readingTime": math::max([1, round(length(pt::text(body)) / 5 / 220)]),  author->{name, "slug": slug.current},  issue->{number, title, "slug": slug.current},  topics[]->{_id, title, "slug": slug.current}},  "recent": *[_type == "article"]    | order(publishedAt desc)[0...13]{  _id,  title,  "slug": slug.current,  standfirst,  publishedAt,  featured,  "readingTime": math::max([1, round(length(pt::text(body)) / 5 / 220)]),  author->{name, "slug": slug.current},  issue->{number, title, "slug": slug.current},  topics[]->{_id, title, "slug": slug.current}},  "latestIssue": *[_type == "issue"] | order(number desc)[0]{    _id,    number,    title,    "slug": slug.current,    publishedAt  }}
export type HomeQueryResult = {
  featured: {
    _id: string;
    title: string;
    slug: string;
    standfirst: string;
    publishedAt: string;
    featured: true;
    readingTime: number | 1;
    author: {
      name: string;
      slug: string;
    };
    issue: {
      number: number;
      title: string;
      slug: string;
    } | null;
    topics: Array<{
      _id: string;
      title: string;
      slug: string;
    }> | null;
  } | null;
  recent: Array<{
    _id: string;
    title: string;
    slug: string;
    standfirst: string;
    publishedAt: string;
    featured: boolean | null;
    readingTime: number | 1;
    author: {
      name: string;
      slug: string;
    };
    issue: {
      number: number;
      title: string;
      slug: string;
    } | null;
    topics: Array<{
      _id: string;
      title: string;
      slug: string;
    }> | null;
  }>;
  latestIssue: {
    _id: string;
    number: number;
    title: string;
    slug: string;
    publishedAt: string;
  } | null;
};

// Source: sanity/lib/queries.ts
// Variable: articleSlugsQuery
// Query: *[_type == "article" && defined(slug.current)].slug.current
export type ArticleSlugsQueryResult = Array<string>;

// Source: sanity/lib/queries.ts
// Variable: articlesQuery
// Query: *[_type == "article"] | order(publishedAt desc){  _id,  title,  "slug": slug.current,  standfirst,  publishedAt,  featured,  "readingTime": math::max([1, round(length(pt::text(body)) / 5 / 220)]),  author->{name, "slug": slug.current},  issue->{number, title, "slug": slug.current},  topics[]->{_id, title, "slug": slug.current}}
export type ArticlesQueryResult = Array<{
  _id: string;
  title: string;
  slug: string;
  standfirst: string;
  publishedAt: string;
  featured: boolean | null;
  readingTime: number | 1;
  author: {
    name: string;
    slug: string;
  };
  issue: {
    number: number;
    title: string;
    slug: string;
  } | null;
  topics: Array<{
    _id: string;
    title: string;
    slug: string;
  }> | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: articleBySlugQuery
// Query: *[_type == "article" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    standfirst,    publishedAt,    body[]{  ...,  _type == "captionedImage" => {  ...,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height, aspectRatio}}  }},  _type == "imageGallery" => {    ...,    images[]{  ...,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height, aspectRatio}}  }}  }},    author->{      name,      "slug": slug.current,      role,      bio    },    issue->{number, title, "slug": slug.current},    topics[]->{_id, title, "slug": slug.current},    seo {..., ogImage {  ...,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height, aspectRatio}}  }}}  }
export type ArticleBySlugQueryResult = {
  _id: string;
  title: string;
  slug: string;
  standfirst: string;
  publishedAt: string;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          {
            _key: string;
          } & Link
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "captionedImage";
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number;
              height: number;
              aspectRatio: number;
            } | null;
          } | null;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        caption?: string;
        credit?: string;
      }
    | {
        _key: string;
        _type: "imageGallery";
        images: Array<{
          _key: string;
          _type: "captionedImage";
          asset: {
            _id: string;
            url: string;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number;
                height: number;
                aspectRatio: number;
              } | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          caption?: string;
          credit?: string;
        }>;
        layout: "grid" | "sideBySide";
      }
    | {
        _key: string;
        _type: "noteAside";
        title: string;
        content: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: never;
          markDefs?: Array<
            {
              _key: string;
            } & Link
          >;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        tone: "caution" | "note";
      }
    | {
        _key: string;
        _type: "pullQuote";
        quote: string;
        attribution?: string;
      }
  > | null;
  author: {
    name: string;
    slug: string;
    role: string | null;
    bio: SimpleText | null;
  };
  issue: {
    number: number;
    title: string;
    slug: string;
  } | null;
  topics: Array<{
    _id: string;
    title: string;
    slug: string;
  }> | null;
  seo: {
    _type: "seo";
    title?: string;
    description?: string;
    ogImage: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
            aspectRatio: number;
          } | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: relatedArticlesQuery
// Query: *[    _type == "article"    && slug.current != $slug    && count(topics[_ref in $topicIds]) > 0  ] | order(publishedAt desc)[0...3]{  _id,  title,  "slug": slug.current,  standfirst,  publishedAt,  featured,  "readingTime": math::max([1, round(length(pt::text(body)) / 5 / 220)]),  author->{name, "slug": slug.current},  issue->{number, title, "slug": slug.current},  topics[]->{_id, title, "slug": slug.current}}
export type RelatedArticlesQueryResult = Array<{
  _id: string;
  title: string;
  slug: string;
  standfirst: string;
  publishedAt: string;
  featured: boolean | null;
  readingTime: number | 1;
  author: {
    name: string;
    slug: string;
  };
  issue: {
    number: number;
    title: string;
    slug: string;
  } | null;
  topics: Array<{
    _id: string;
    title: string;
    slug: string;
  }> | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: issueSlugsQuery
// Query: *[_type == "issue" && defined(slug.current)].slug.current
export type IssueSlugsQueryResult = Array<string>;

// Source: sanity/lib/queries.ts
// Variable: issuesQuery
// Query: *[_type == "issue"] | order(number desc){    _id,    number,    title,    "slug": slug.current,    publishedAt,    "articleCount": count(*[_type == "article" && issue._ref == ^._id])  }
export type IssuesQueryResult = Array<{
  _id: string;
  number: number;
  title: string;
  slug: string;
  publishedAt: string;
  articleCount: number;
}>;

// Source: sanity/lib/queries.ts
// Variable: issueBySlugQuery
// Query: *[_type == "issue" && slug.current == $slug][0]{    _id,    number,    title,    "slug": slug.current,    publishedAt,    colophon,    introduction[]{  ...,  _type == "captionedImage" => {  ...,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height, aspectRatio}}  }},  _type == "imageGallery" => {    ...,    images[]{  ...,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height, aspectRatio}}  }}  }},    "articles": *[_type == "article" && issue._ref == ^._id]      | order(publishedAt asc){  _id,  title,  "slug": slug.current,  standfirst,  publishedAt,  featured,  "readingTime": math::max([1, round(length(pt::text(body)) / 5 / 220)]),  author->{name, "slug": slug.current},  issue->{number, title, "slug": slug.current},  topics[]->{_id, title, "slug": slug.current}}  }
export type IssueBySlugQueryResult = {
  _id: string;
  number: number;
  title: string;
  slug: string;
  publishedAt: string;
  colophon: string | null;
  introduction: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          {
            _key: string;
          } & Link
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "captionedImage";
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number;
              height: number;
              aspectRatio: number;
            } | null;
          } | null;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        caption?: string;
        credit?: string;
      }
    | {
        _key: string;
        _type: "imageGallery";
        images: Array<{
          _key: string;
          _type: "captionedImage";
          asset: {
            _id: string;
            url: string;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number;
                height: number;
                aspectRatio: number;
              } | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          caption?: string;
          credit?: string;
        }>;
        layout: "grid" | "sideBySide";
      }
    | {
        _key: string;
        _type: "noteAside";
        title: string;
        content: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: never;
          markDefs?: Array<
            {
              _key: string;
            } & Link
          >;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        tone: "caution" | "note";
      }
    | {
        _key: string;
        _type: "pullQuote";
        quote: string;
        attribution?: string;
      }
  > | null;
  articles: Array<{
    _id: string;
    title: string;
    slug: string;
    standfirst: string;
    publishedAt: string;
    featured: boolean | null;
    readingTime: number | 1;
    author: {
      name: string;
      slug: string;
    };
    issue: {
      number: number;
      title: string;
      slug: string;
    } | null;
    topics: Array<{
      _id: string;
      title: string;
      slug: string;
    }> | null;
  }>;
} | null;

// Source: sanity/lib/queries.ts
// Variable: topicSlugsQuery
// Query: *[_type == "topic" && defined(slug.current)].slug.current
export type TopicSlugsQueryResult = Array<string>;

// Source: sanity/lib/queries.ts
// Variable: topicsQuery
// Query: *[_type == "topic"] | order(title asc){    _id,    title,    "slug": slug.current,    description,    "articleCount": count(*[_type == "article" && ^._id in topics[]._ref])  }
export type TopicsQueryResult = Array<{
  _id: string;
  title: string;
  slug: string;
  description: string | null;
  articleCount: number;
}>;

// Source: sanity/lib/queries.ts
// Variable: topicBySlugQuery
// Query: *[_type == "topic" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    description,    "articles": *[_type == "article" && ^._id in topics[]._ref]      | order(publishedAt desc){  _id,  title,  "slug": slug.current,  standfirst,  publishedAt,  featured,  "readingTime": math::max([1, round(length(pt::text(body)) / 5 / 220)]),  author->{name, "slug": slug.current},  issue->{number, title, "slug": slug.current},  topics[]->{_id, title, "slug": slug.current}}  }
export type TopicBySlugQueryResult = {
  _id: string;
  title: string;
  slug: string;
  description: string | null;
  articles: Array<{
    _id: string;
    title: string;
    slug: string;
    standfirst: string;
    publishedAt: string;
    featured: boolean | null;
    readingTime: number | 1;
    author: {
      name: string;
      slug: string;
    };
    issue: {
      number: number;
      title: string;
      slug: string;
    } | null;
    topics: Array<{
      _id: string;
      title: string;
      slug: string;
    }> | null;
  }>;
} | null;

// Source: sanity/lib/queries.ts
// Variable: authorSlugsQuery
// Query: *[_type == "author" && defined(slug.current)].slug.current
export type AuthorSlugsQueryResult = Array<string>;

// Source: sanity/lib/queries.ts
// Variable: authorBySlugQuery
// Query: *[_type == "author" && slug.current == $slug][0]{    _id,    name,    "slug": slug.current,    role,    bio,    links[]{label, url},    "articles": *[_type == "article" && author._ref == ^._id]      | order(publishedAt desc){  _id,  title,  "slug": slug.current,  standfirst,  publishedAt,  featured,  "readingTime": math::max([1, round(length(pt::text(body)) / 5 / 220)]),  author->{name, "slug": slug.current},  issue->{number, title, "slug": slug.current},  topics[]->{_id, title, "slug": slug.current}}  }
export type AuthorBySlugQueryResult = {
  _id: string;
  name: string;
  slug: string;
  role: string | null;
  bio: SimpleText | null;
  links: Array<{
    label: string;
    url: string;
  }> | null;
  articles: Array<{
    _id: string;
    title: string;
    slug: string;
    standfirst: string;
    publishedAt: string;
    featured: boolean | null;
    readingTime: number | 1;
    author: {
      name: string;
      slug: string;
    };
    issue: {
      number: number;
      title: string;
      slug: string;
    } | null;
    topics: Array<{
      _id: string;
      title: string;
      slug: string;
    }> | null;
  }>;
} | null;

// Source: sanity/lib/queries.ts
// Variable: pageSlugsQuery
// Query: *[_type == "page" && defined(slug.current)].slug.current
export type PageSlugsQueryResult = Array<string>;

// Source: sanity/lib/queries.ts
// Variable: pageBySlugQuery
// Query: *[_type == "page" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    body[]{  ...,  _type == "captionedImage" => {  ...,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height, aspectRatio}}  }},  _type == "imageGallery" => {    ...,    images[]{  ...,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height, aspectRatio}}  }}  }},    seo {..., ogImage {  ...,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height, aspectRatio}}  }}}  }
export type PageBySlugQueryResult = {
  _id: string;
  title: string;
  slug: string;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          {
            _key: string;
          } & Link
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "captionedImage";
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number;
              height: number;
              aspectRatio: number;
            } | null;
          } | null;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        caption?: string;
        credit?: string;
      }
    | {
        _key: string;
        _type: "imageGallery";
        images: Array<{
          _key: string;
          _type: "captionedImage";
          asset: {
            _id: string;
            url: string;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number;
                height: number;
                aspectRatio: number;
              } | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          caption?: string;
          credit?: string;
        }>;
        layout: "grid" | "sideBySide";
      }
    | {
        _key: string;
        _type: "noteAside";
        title: string;
        content: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: never;
          markDefs?: Array<
            {
              _key: string;
            } & Link
          >;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        tone: "caution" | "note";
      }
    | {
        _key: string;
        _type: "pullQuote";
        quote: string;
        attribution?: string;
      }
  > | null;
  seo: {
    _type: "seo";
    title?: string;
    description?: string;
    ogImage: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
            aspectRatio: number;
          } | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
} | null;
